Visible
eclipse-cdt-cloud/timeline-chart pull request #197
Opened 2022-04-28 18:52 UTC by PatrickTasse

2022-05-03 15:50 UTC, bhufmann requested changes
Thanks for the improvement. It works quite well. However, I have some initial findings that need to be fixed.

2022-05-05 18:56 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-chart.ts
>                      this.addElementInteractions(el);
I think this one should stay addElementInteractions, it's also used for annotations. And maybe eventually for arrows?

2022-05-05 19:05 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-chart.ts
> +        if (this.rowIds.length > 0) {
I added a description at the declaration.

2022-05-09 14:12 UTC, bhufmann requested changes
I have one question left. The commit messages doesn't mention about the code for arrow-up/down navigation being moved to another class. Please add it.

2022-05-09 19:11 UTC, bhufmann commented
> I have one question left. The commit messages doesn't mention about the code for arrow-up/down navigation being moved to another class. Please add it.

I missed it the commit message. It's already there

2022-05-09 19:20 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-chart.ts
> +    rowProvider: () => { rowIds: number[] }
The implementation of rowProvider in theia-trace-extension returns immediately from an already-fetched tree model, it does not need to communicate with the trace-server.

Further, making this async would require adding protection against out-of-order responses.

For these reasons I think it's best not to change to a Promise.

2022-05-09 19:35 UTC, bhufmann commented on timeline-chart/src/layer/time-graph-chart.ts
> +    rowProvider: () => { rowIds: number[] }
Ok, thanks for the explanation.

2022-05-09 19:37 UTC, bhufmann approved these changes
Looks good to me. Works well with the theia-trace-extension integration and brings performance improvements for it.

2022-05-09 21:39 UTC, Rodrigoplp-work approved these changes

2022-05-10 17:33 UTC, merged