Add support for configurable location of time axis ticks
eclipse-cdt-cloud/timeline-chart pull request #206
Opened 2022-06-08 21:08 UTC by hoangphamEclipse

This commit adds support for configurable location of time axis ticks. Currently, the ticks can only be displayed above the time labels in the time axis, which do not make sense UI-wise when we have graphs that are displayed under the time axis. This commit allows the ticks of the time axis to be displayed dynamically either on top or under the time labels by adding a configuration parameter to the TimeGraphAxisScale component, so that developers can position the ticks correctly.

Resolve: [Issue 203](https://github.com/eclipse-cdt-cloud/timeline-chart/issues/203) and  [Issue 755](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/755) of the Theia Trace Extension.

2022-06-09 18:11 UTC, bhufmann requested changes
It looks good and it works well. I tested it with the theia-trace-extension. I have one suggestion, please change the vertical alignment of the example to bottom (see index.ts). With both configurations are available in the example and axis test.

2022-06-09 20:24 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-axis.ts
> +    constructor(id: string, protected style?: { color?: number, lineColor?: number, verticalLinePosition?: VerticalLinePosition }) {
To me it seems odd that the external user of TimeGraphAxis needs to import the type used in the constructor from an internal component. Seems like it should be defined in this class.

2022-06-10 15:06 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-axis.ts
> +    constructor(id: string, protected style?: { color?: number, lineColor?: number, verticalLinePosition?: VerticalLinePosition }) {
What I would suggest is to have it as top?: boolean.

So by default, the axis is at the bottom (like an normal chart).

Then, this layer will use the boolean to set the verticalLinePosition.
top=true -> VerticalLinePosition.BOTTOM
else -> VerticalLinePosition.TOP

2022-06-13 17:13 UTC, bhufmann commented
@hoangphamEclipse is this PR ready for review? I'm asking because it's marked as draft.

2022-06-13 17:14 UTC, hoangphamEclipse commented
@bhufmann Yes it is ready for review. Sorry I forget to revert it back to Ready for review.

2022-06-13 17:45 UTC, PatrickTasse requested changes

2022-06-13 17:45 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-axis.ts
> +    constructor(id: string, protected style?: { color?: number, lineColor?: number, isTop?: boolean }) {
Sorry, we had further discussion and we would suggest that we use the vertical-align string property from CSS (verticalAlign in code):

https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

So if you align to the top, that means you stick to the top of your layout cell, then the ticks should be on top.
If you align to the bottom the ticks should be at the bottom.

Looking at the link above, it seems their default is 'baseline' and in the example that aligns to the top. So perhaps we could default to 'top'.

<pre>
+---|---|---|---+
|   1   2   3   |  verticalAlign = 'top'
|               |
+---------------+

+---------------+
|               |
|   1   2   3   |  verticalAlign = 'bottom'
+---|---|---|---+
</pre>

2022-06-16 14:43 UTC, PatrickTasse approved these changes

2022-06-16 14:57 UTC, bhufmann approved these changes
Looks good! Thanks

2022-06-16 15:10 UTC, merged