Selected Row Visibility
eclipse-cdt-cloud/timeline-chart pull request #209
Opened 2022-07-11 23:27 UTC by williamsyang-work

Adds public method TimelineChart#selectRowFromId that sets the selected
row using an ID number as a pointer.

Fixes a bug where background color information wasn't being stored
correctly for time-graph-row.

(I think some linting happened in this PR.  I will comment at the relevant changes.  I can re-create this branch without the linting changes as well.)

Fixes: #774, #772

Signed-off-by: Will Yang <william.yang@ericsson.com>

2022-07-11 23:28 UTC, williamsyang-work commented on timeline-chart/src/layer/time-graph-chart.ts
> +    selectRow = (row: TimelineChart.TimeGraphRowModel | undefined) => {
Method defined with fat-arrow notation to bind the context of "this".

2022-07-11 23:29 UTC, williamsyang-work commented on timeline-chart/src/layer/time-graph-chart.ts
> +    };
Public method to set the selected row from the row's ID #.

2022-07-11 23:29 UTC, williamsyang-work commented on timeline-chart/src/components/time-graph-row.ts
> +            this._style.backgroundColor = style.backgroundColor;
Adding this allows for the background color to be changed.

2022-07-20 13:02 UTC, bhufmann requested changes

2022-07-22 14:36 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2022-07-22 14:39 UTC, merged