Center rows when selected
eclipse-cdt-cloud/timeline-chart pull request #211
Opened 2022-08-30 01:43 UTC by williamsyang-work

Adds the method TimeGraphChart#centerRow which has logic to adjust the vertical offset to center a row given it's index.

Fixes: [theia-trace-extension #773](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/773)

Signed-off-by: Will Yang <william.yang@ericsson.com>

2022-09-12 14:33 UTC, bhufmann approved these changes
Looks good to me. @PatrickTasse could you please have review in respect of the visible rows and background fetching implementation.

2022-09-12 15:17 UTC, PatrickTasse requested changes

2022-09-12 15:50 UTC, williamsyang-work commented on timeline-chart/src/layer/time-graph-chart.ts
> +        center ? this.centerRow(rowIndex) : this.ensureVisible(rowIndex);
I didn't realize navigate was called even when a row is clicked in the timeline-chart.  That is annoying behavior... Nice catch.

2022-09-12 15:57 UTC, williamsyang-work commented on timeline-chart/src/layer/time-graph-chart.ts
> +        center ? this.centerRow(rowIndex) : this.ensureVisible(rowIndex);
For the horizontal scrollbar issue, that's only applicable if only one chart component is open.  IE, if we have multiple open, that only applies to the bottom one.

![image](https://user-images.githubusercontent.com/98342456/189700520-4c587d91-e4f4-4cea-89f3-e052e16e2b81.png)

2022-09-13 17:10 UTC, PatrickTasse approved these changes

2022-09-13 17:58 UTC, bhufmann approved these changes

2022-09-13 17:58 UTC, merged