Ci publish: Add release workflow/job, publish-latest job
eclipse-cdt-cloud/timeline-chart pull request #270
Opened 2024-02-14 16:31 UTC by marcdumais-work

The new release workflow uses action "pipe-cd/actions-gh-release". This action uses file RELEASE in the root. When that file is modified in a PR, and contains a new release tag, it will trigger a release upon the PR being merged. The action will create a git tag in the repo and the corresponding GitHub release, containing auto-generated release notes, that can be later edited by a committer.
    
The new release will in turn trigger the new "publish-latest" job (ci-cd workflow), which will publish the new version of the package to npm.

Also made little improvements to package.json

2024-02-14 22:04 UTC, marcdumais-work commented on package.json
> +        "publish:latest:ci": "lerna run publish:latest:ci",
I could not get lerna to publish a "latest" without prompting for the user to select a version. So instead I call a script from the deeper package.json, and there use "yarm publish --non-interactive [...]" to accomplish theat goal.

2024-02-14 22:05 UTC, marcdumais-work commented on package.json
> +        "publish:latest:manual": "lerna publish --registry=https://registry.npmjs.org/ --exact --no-git-tag-version --no-push --yes",
I was not sure, but I thought it could still be useful for now to be able to manually publish, so I kept this script but renamed it to ":manual"

2024-02-14 22:07 UTC, marcdumais-work commented
I successfully tested locally, publishing to a npm registry, using `verdaccio`.

2024-02-29 21:08 UTC, marcdumais-work commented on lerna.json
> +  "version": "independent",
no longer relevant

2024-02-29 21:09 UTC, marcdumais-work commented on package.json
> +        "publish:latest:ci": "lerna run publish:latest:ci",
no longer relevant

2024-03-01 15:21 UTC, marcdumais-work commented
I have tested `yarn publish:latest:ci` locally using `verdaccio` and it seems to work.

2024-03-01 16:08 UTC, bhufmann requested changes
small change needed

2024-03-01 16:10 UTC, marcdumais-work commented on timeline-chart/package.json
> +  "homepage": "https://github.com/theia-ide/timeline-chart",
oops - good catch

2024-03-01 16:16 UTC, bhufmann approved these changes
Thanks for the contribution!

2024-03-01 16:52 UTC, marcdumais-work commented
Thanks for the review!

2024-03-01 16:52 UTC, merged